name: Build & Send Daily Brief

on:
  schedule:
    # 10:00 UTC = 5 a.m. CT
    - cron:  "0 10 * * *"
  workflow_dispatch:  # allows manual runs

jobs:
  run-newsbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --quiet sendgrid google-api-python-client google-auth openai pytz

      - name: Execute script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
          FILE_ID: ${{ secrets.FILE_ID }}
          SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
          SUBSTACK_IN_ADDR: ${{ secrets.SUBSTACK_IN_ADDR }}
        run: python newsbot.py
